root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go run scripts/build.go && go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
include_ext = ["go", "templ", "ts", "tsx"]
exclude_regex = ["_templ\\.go$"]
exclude_dir = ["tmp", "node_modules", "web/dist"]
delay = 1000

[misc]
clean_on_exit = true
